LANGUAGES = {
    "ru": {
        "language_name": "Русский",
        # Меню/общие
        "app_name": "Mirage",
        "pause": "Пауза",
        "resume": "Продолжить",
        "next": "Следующая картинка",
        "settings": "Настройки…",
        "quit": "Выход",
        "menu_language": "Язык",
        # Настройки
        "settings_title": "Настройки",
        "folder_label": "Папка с изображениями:",
        "interval_label": "Интервал (минуты):",
        "shuffle": "Случайный порядок",
        "recursive": "Рекурсивно по подпапкам",
        "use_selected": "Только выбранные изображения (если список не пустой)",
        "pick_images": "Выбрать изображения…",
        "selected_count": "Выбрано изображений: {count}",
        "current_wallpaper": "Текущие обои",
        "btn_save": "Сохранить",
        "btn_cancel": "Отмена",
        "formats_label": "Форматы",
        "images_filter_title": "Изображения",
        "filter_all": "Все файлы",
        "autostart": "Автозапуск",
        "website_label": "GitHub: Mirage",
    },
    "en": {
        "language_name": "English",
        # Menu/common
        "app_name": "Mirage",
        "pause": "Pause",
        "resume": "Resume",
        "next": "Next wallpaper",
        "settings": "Settings…",
        "quit": "Quit",
        "menu_language": "Language",
        # Settings
        "settings_title": "Settings",
        "folder_label": "Images folder:",
        "interval_label": "Interval (minutes):",
        "shuffle": "Shuffle order",
        "recursive": "Include subfolders",
        "use_selected": "Use only selected images (if list not empty)",
        "pick_images": "Pick images…",
        "selected_count": "Selected images: {count}",
        "current_wallpaper": "Current wallpaper",
        "btn_save": "Save",
        "btn_cancel": "Cancel",
        "formats_label": "Formats",
        "images_filter_title": "Images",
        "filter_all": "All files",
        "autostart": "Autostart",
        "website_label": "GitHub: Mirage",
    },
}