LANGUAGES = {
    "ru": {
        "language_name": "🇷🇺 Русский",
        # Меню/общие
        "app_name": "Mirage",
        "pause": "Пауза",
        "resume": "Продолжить",
        "next": "Следующая картинка",
        "settings": "Настройки…",
        "quit": "Выход",
        "menu_language": "Язык",
        # Настройки
        "settings_title": "Настройки",
        "folder_label": "Папка с изображениями:",
        "interval_label": "Интервал (минуты):",
        "shuffle": "Случайный порядок",
        "recursive": "Рекурсивно по подпапкам",
        "use_api_random": "Случайные обои через API",
        "use_selected": "Только выбранные изображения (если список не пустой)",
        "pick_images": "Выбрать изображения…",
        "selected_count": "Выбрано изображений: {count}",
        "current_wallpaper": "Текущие обои",
        "btn_save": "Сохранить",
        "btn_cancel": "Отмена",
        "formats_label": "Форматы",
        "images_filter_title": "Изображения",
        "filter_all": "Все файлы",
        "website_label": "GitHub: Mirage",
        "tab_general": "Общие",
        "tab_sources": "Источники",
        "tab_preview": "Предпросмотр",
    },
    "en": {
        "language_name": "🇬🇧 English",
        # Menu/common
        "app_name": "Mirage",
        "pause": "Pause",
        "resume": "Resume",
        "next": "Next wallpaper",
        "settings": "Settings…",
        "quit": "Quit",
        "menu_language": "Language",
        # Settings
        "settings_title": "Settings",
        "folder_label": "Images folder:",
        "interval_label": "Interval (minutes):",
        "shuffle": "Shuffle order",
        "recursive": "Include subfolders",
        "use_api_random": "Use random wallpapers via API",
        "use_selected": "Use only selected images (if list not empty)",
        "pick_images": "Pick images…",
        "selected_count": "Selected images: {count}",
        "current_wallpaper": "Current wallpaper",
        "btn_save": "Save",
        "btn_cancel": "Cancel",
        "formats_label": "Formats",
        "images_filter_title": "Images",
        "filter_all": "All files",
        "website_label": "GitHub: Mirage",
        "tab_general": "General",
        "tab_sources": "Sources",
        "tab_preview": "Preview",
    },
    "cn": {
        "language_name": "🇨🇳 中文",
        # 菜单/通用
        "app_name": "Mirage",
        "pause": "暂停",
        "resume": "继续",
        "next": "下一张壁纸",
        "settings": "设置…",
        "quit": "退出",
        "menu_language": "语言",
        # 设置
        "settings_title": "设置",
        "folder_label": "图片文件夹:",
        "interval_label": "间隔（分钟）:",
        "shuffle": "随机顺序",
        "recursive": "包含子文件夹",
        "use_api_random": "通过 API 使用随机壁纸",
        "use_selected": "仅使用已选图片（当列表非空时）",
        "pick_images": "选择图片…",
        "selected_count": "已选图片: {count}",
        "current_wallpaper": "当前壁纸",
        "btn_save": "保存",
        "btn_cancel": "取消",
        "formats_label": "格式",
        "images_filter_title": "图片",
        "filter_all": "所有文件",
        "website_label": "GitHub: Mirage",
    },
    "de": {
        "language_name": "🇩🇪 Deutsch",
        # Menü/Allgemein
        "app_name": "Mirage",
        "pause": "Pausieren",
        "resume": "Fortsetzen",
        "next": "Nächstes Hintergrundbild",
        "settings": "Einstellungen…",
        "quit": "Beenden",
        "menu_language": "Sprache",
        # Einstellungen
        "settings_title": "Einstellungen",
        "folder_label": "Bildordner:",
        "interval_label": "Intervall (Minuten):",
        "shuffle": "Zufällige Reihenfolge",
        "recursive": "Unterordner einbeziehen",
        "use_api_random": "Zufällige Hintergrundbilder per API verwenden",
        "use_selected": "Nur ausgewählte Bilder verwenden (wenn Liste nicht leer ist)",
        "pick_images": "Bilder auswählen…",
        "selected_count": "Ausgewählte Bilder: {count}",
        "current_wallpaper": "Aktuelles Hintergrundbild",
        "btn_save": "Speichern",
        "btn_cancel": "Abbrechen",
        "formats_label": "Formate",
        "images_filter_title": "Bilder",
        "filter_all": "Alle Dateien",
        "website_label": "GitHub: Mirage",
    },
    "it": {
        "language_name": "🇮🇹 Italiano",
        # Menu/comune
        "app_name": "Mirage",
        "pause": "Pausa",
        "resume": "Riprendi",
        "next": "Sfondo successivo",
        "settings": "Impostazioni…",
        "quit": "Esci",
        "menu_language": "Lingua",
        # Impostazioni
        "settings_title": "Impostazioni",
        "folder_label": "Cartella immagini:",
        "interval_label": "Intervallo (minuti):",
        "shuffle": "Ordine casuale",
        "recursive": "Includi sottocartelle",
        "use_api_random": "Usa sfondi casuali tramite API",
        "use_selected": "Usa solo immagini selezionate (se la lista non è vuota)",
        "pick_images": "Seleziona immagini…",
        "selected_count": "Immagini selezionate: {count}",
        "current_wallpaper": "Sfondo corrente",
        "btn_save": "Salva",
        "btn_cancel": "Annulla",
        "formats_label": "Formati",
        "images_filter_title": "Immagini",
        "filter_all": "Tutti i file",
        "website_label": "GitHub: Mirage",
    },
    "es": {
        "language_name": "🇪🇸 Español",
        # Menú/común
        "app_name": "Mirage",
        "pause": "Pausar",
        "resume": "Continuar",
        "next": "Siguiente fondo",
        "settings": "Configuración…",
        "quit": "Salir",
        "menu_language": "Idioma",
        # Configuración
        "settings_title": "Configuración",
        "folder_label": "Carpeta de imágenes:",
        "interval_label": "Intervalo (minutos):",
        "shuffle": "Orden aleatorio",
        "recursive": "Incluir subcarpetas",
        "use_api_random": "Usar fondos aleatorios mediante API",
        "use_selected": "Usar solo imágenes seleccionadas (si la lista no está vacía)",
        "pick_images": "Elegir imágenes…",
        "selected_count": "Imágenes seleccionadas: {count}",
        "current_wallpaper": "Fondo actual",
        "btn_save": "Guardar",
        "btn_cancel": "Cancelar",
        "formats_label": "Formatos",
        "images_filter_title": "Imágenes",
        "filter_all": "Todos los archivos",
        "website_label": "GitHub: Mirage",
    },
    "tr": {
        "language_name": "🇹🇷 Türkçe",
        # Menü/genel
        "app_name": "Mirage",
        "pause": "Duraklat",
        "resume": "Devam et",
        "next": "Sonraki duvar kâğıdı",
        "settings": "Ayarlar…",
        "quit": "Çıkış",
        "menu_language": "Dil",
        # Ayarlar
        "settings_title": "Ayarlar",
        "folder_label": "Görsel klasörü:",
        "interval_label": "Aralık (dakika):",
        "shuffle": "Karışık sıra",
        "recursive": "Alt klasörleri dahil et",
        "use_api_random": "API ile rastgele duvar kâğıtları kullan",
        "use_selected": "Yalnızca seçili görselleri kullan (liste boş değilse)",
        "pick_images": "Görselleri seç…",
        "selected_count": "Seçilen görseller: {count}",
        "current_wallpaper": "Mevcut duvar kâğıdı",
        "btn_save": "Kaydet",
        "btn_cancel": "İptal",
        "formats_label": "Biçimler",
        "images_filter_title": "Görseller",
        "filter_all": "Tüm dosyalar",
        "website_label": "GitHub: Mirage",
    },
    "fr": {
        "language_name": "🇫🇷 Français",
        # Menu/commun
        "app_name": "Mirage",
        "pause": "Pause",
        "resume": "Reprendre",
        "next": "Fond d’écran suivant",
        "settings": "Paramètres…",
        "quit": "Quitter",
        "menu_language": "Langue",
        # Paramètres
        "settings_title": "Paramètres",
        "folder_label": "Dossier d’images :",
        "interval_label": "Intervalle (minutes) :",
        "shuffle": "Ordre aléatoire",
        "recursive": "Inclure les sous-dossiers",
        "use_api_random": "Utiliser des fonds aléatoires via API",
        "use_selected": "Utiliser uniquement les images sélectionnées (si la liste n’est pas vide)",
        "pick_images": "Choisir des images…",
        "selected_count": "Images sélectionnées : {count}",
        "current_wallpaper": "Fond d’écran actuel",
        "btn_save": "Enregistrer",
        "btn_cancel": "Annuler",
        "formats_label": "Formats",
        "images_filter_title": "Images",
        "filter_all": "Tous les fichiers",
        "website_label": "GitHub: Mirage",
    },
}
